version: '3.8'

services:
  mongo:
    image: mongo:4
    container_name: mongo
    restart: unless-stopped
    environment:
      #MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_USERNAME: mongo
      #MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017

  express:
    container_name: express
    image: mongo-express
    restart: unless-stopped
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      #ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    links:
      - mongo
    ports:
      - 8071:8081
