services:
  mongo:
    image: mongo:8.0.4
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      # MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_USERNAME: mongo
      # MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_ROOT_PASSWORD: mongo

  express:
    container_name: express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    ports:
      - 8071:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      # ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    links:
      - mongo
