version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: unless-stopped
    environment:
      #POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_USER: postgres
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB: postgres
    volumes:
      - ./:/docker-entrypoint-initdb.d/
      #- /var/stack/postgresql/:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pga:
    container_name: pga
    image: dpage/pgadmin4:4
    environment:
      #PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_EMAIL: postgres@postgre.sql
      #PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DEFAULT_PASSWORD: postgres
    links:
      - postgres
    restart: unless-stopped
    ports:
      - 8070:80
