version: '3'
services:
  rabbitmq:
    image: rabbitmq:ui
    build: .
    container_name: rabbitmq-ui
    restart: unless-stopped
    environment:
      #RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_USER: guest
      #RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_PASS: guest
    ports:
    - 4369:4369
    - 5671:5671
    - 5672:5672
    - 15672:15672
